---
HOST_URL: http://20.221.80.17/:8080
OKTAURL: https://dev-00143999.okta.com
OKTAID: 0oa4hlf6pcsq092Tl5d7
OKTASECRET: BD9HdiYcxRTt_51X5v5nfpe1jBVtwLeMeb6-9hHE
PGHOST: 10.0.1.4
PGUSERNAMEE: postgres
PGDBNAME: postgres
PGPASS: dsadsawefff3423#34!
PGPORT: 5432