---
HOST_URL: http://<LoadBalancerIP>:8080
OKTAURL: https://<YourOktaDomain>
OKTAID: <YourOktaID>
OKTASECRET: <YourOktaSecret>
PGHOST: 10.0.1.4
PGUSERNAMEE: postgres
PGDBNAME: postgres
PGPASS: <YourPasswordFromAbove>
PGPORT: 5432
