---
HOST_URL: http://52.154.161.166:8080
OKTAURL: https://dev-00143999.okta.com
OKTAID: 0oa4h7zgciC00EaRN5d7
OKTASECRET: 5mdYXuISzkKK5k2PXWo-5QfxdGl-bSHCmEMH3OQh
PGHOST: 10.0.1.4
PGUSERNAMEE: postgres
PGDBNAME: postgres
PGPASS: dsadsawefff3423#34!
PGPORT: 5432