---
HOST_URL: http://20.236.193.91/:8080
OKTAURL: https://dev-00143999.okta.com
OKTAID: 0oa4hl50n5m2iwvZL5d7
OKTASECRET: traUBCPAb6ycM0LJebzVgFerZCww1y7DkwvtSBfn
PGHOST: 10.0.1.4
PGUSERNAMEE: postgres
PGDBNAME: postgres
PGPASS: dsadsawefff3423#34!
PGPORT: 5432