---

   - name: Copy file with owner and permissions
        ansible.builtin.copy:
                            src: /home/Ansible-Controler/myagent/_work/1/files/s/newimage.tar
                            dest: /home/adminuser/newimage.tar
                            owner: ubuntu
                            group: ubuntu
                            mode: '0600'
        become: true
   
   
   - name: Transfer file from ServerA to ServerB
     synchronize:
       src: /home/Ansible-Controler/myagent/_work/1/files/s/newimage.tar
       dest: /home/adminuser/
       
       
   
  
