---

 
   
   
   - name: Copy file with owner and permissions
     ansible.builtin.copy:
       src: /home/Ansible-Controler/myagent/_work/1/files/s/newimage.tar
       dest: /home/adminuser/newimage.tar
       owner: foo
       group: foo
       mode: '0644'
   
   
   
   - name: Transfer file from ServerA to ServerB
     synchronize:
       src: /home/Ansible-Controler/myagent/_work/1/files/s/newimage.tar
       dest: /home/adminuser/
       
       
   
  
