---

 
  
    
   - name: Transfer file from ServerA to ServerB
     synchronize:
       src: /home/Ansible-Controler/myagent/_work/1/s/newimage.tar
       dest: /home/adminuser/
    
   
   - name: untar the file
     shell: docker load -i newimage.tar
     args:
       chdir: /home/adminuser/
       
   
   - name: deleting last images
     shell: docker rm -f $(docker ps -qa)
     args:
       chdir: /home/adminuser/ 
   
   
   - name: running the image
     shell: docker run -d -p 8080:8080 -d --name=bootcamp   newimage:latest
     args:
       chdir: /home/adminuser/    
       

  
