---


   - name: Transfer file from ServerA to ServerB
     synchronize:
       src: /home/Ansible-Controler/myagent/_work/1/files/s/newimage.tar
       dest: /home/adminuser/bootcamp-app
       
       
   - name: PM2 npm
     become: yes
     command: "npm install pm2 -g"
     args:
         chdir: /home/adminuser/bootcamp-app
  
