---

   - name: add nodejs apt key
     apt_key:
       url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
       state: present

   - name: add nodejs 14.x repository
     apt_repository:
       repo: deb https://deb.nodesource.com/node_14.x {{ ansible_lsb.codename }} main
       state: present
       update_cache: yes

   - name: install nodejs 14.x
     apt:
       name: nodejs
       state: present

   - name: clone the weight tracker app folder
     git:
       repo: "https://github.com/GuyR53/bootcamp-app.git"
       dest: /home/adminuser/bootcamp-app
       force: yes

   - name: create .env file
     copy:
        dest: "./bootcamp-app/.env"
        content: |
           # Host Configurations
           
           HOST_URL={{ HOST_URL }}
           COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
           NODE_ENV=development
           
           # Okta configuration
           
           OKTA_ORG_URL=https:{{ OKTAURL}}
           OKTA_CLIENT_ID={{ OKTAID }}
           OKTA_CLIENT_SECRET={{ OKTASECRET  }}
           
           # Postgres Copnfigurations
           
           PGHOST={{ PGHOSTNAME }}
           PGUSERNAME={{ PGUSERNAMEE }}
           PGDATABASE={{ PGDBNAME }}
           PGPASSWORD={{ PGPASS }}
           PGPORT={{ PGPORT }}

   - name: install dependencies
     become: yes
     command: "npm install {{ item }}"
     args:
       chdir: /bootcamp-app
       with_items:
         - '@hapi/hapi@19'
         - '@hapi/bell@12'
         - '@hapi/boom@9'
         - '@hapi/cookie@11'
         - '@hapi/inert@6'
         - '@hapi/joi@17'
         - '@hapi/vision@6'
         - 'dotenv@8'
         - 'ejs@3'
         - 'postgres@1'
         - 'nodemon@2'