---

 
  
    
   - name: Transfer file from ServerA to ServerB
     synchronize:
       src: /home/Ansible-Controler/myagent/_work/1/s/newimage.tar
       dest: /home/adminuser/
   
   
   - name: untar the file
     shell: docker load -i newimage.tar
     args:
       chdir: /home/adminuser/
       
   
   - name: deleting last images
     shell: docker rm -f $(docker ps -qa)
     args:
       chdir: /home/adminuser/ 
   
   
   - name: running the image
     shell: sudo docker run -d -p 8080:8080 newimage 
     args:
       chdir: /home/adminuser/ 
       
   - name: initdb
     shell: sudo docker exec $(sudo docker ps -aq) npm run initdb
     args:
       chdir: /home/adminuser/     
    

   
   
       
   - name: docker would be running always
     shell: sudo docker update --restart unless-stopped $(docker ps -qa)
     args:
       chdir: /home/adminuser/      
   

  
