---
HOST_URL: http://20.85.173.17:8080
OKTAURL: https://dev-00143999.okta.com
OKTAID: 0oa4hm0cj3RCKHrkt5d7
OKTASECRET: Eqwpdq0E6KmrXKMj0sWVWWEkJm3kzbcEctEJg4Bw
PGHOST: 10.0.1.4
PGUSERNAMEE: postgres
PGDBNAME: postgres
PGPASS: dsadsawefff3423#34!
PGPORT: 5432